# key|mountpoint|repo-destination

Admin|/mnt/yodeck-admin|_Yodeck-HTML-Slideshow_Admin/images
VillagePublic|/mnt/yodeck-villagepublic|_Yodeck-HTML-Slideshow_VillagePublic/images

# Existing sections
PolicePublic|/mnt/yodeck-policepublic|_Yodeck-HTML-Slideshow_PolicePublic/images
PoliceEmployee|/mnt/yodeck-policeemployee|_Yodeck-HTML-Slideshow_PoliceEmployee/images

# Planned sections
Fire|/mnt/yodeck-fire|_Yodeck-HTML-Slideshow_Fire/images
FirePrevention|/mnt/yodeck-fireprevention|_Yodeck-HTML-Slideshow_FirePrevention/images
REMA|/mnt/yodeck-rema|_Yodeck-HTML-Slideshow_REMA/images
REC|/mnt/yodeck-rec|_Yodeck-HTML-Slideshow_REC/images
AquaticCenter|/mnt/yodeck-aquaticcenter|_Yodeck-HTML-Slideshow_AquaticCenter/images
RAEC|/mnt/yodeck-raec|_Yodeck-HTML-Slideshow_RAEC/images
PublicWorksAdmin|/mnt/yodeck-publicworksadmin|_Yodeck-HTML-Slideshow_PublicWorksAdmin/images
